[http.middlewares.simpleAuth.basicAuth]
  users = [
    "raju:$apr1$xD70mgR.$tCcipo4PXscDsxh.3L98a0/"
  ]

[http.routers.api]
  rule = "Host(`192.168.43.32`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

